### PR TITLE
NCAS-2374 #comment tried to fix errors introduced during previous mer…

### PR DESCRIPTION
**Pull request by burtonquantil**
…ge on Github by re-checking in file

### CODE REVIEW

**Comment by burtonquantil** [comment]
@nibinqtl  GitHub is complaining about conflicting files though I don't know why.  Last time, I tried to use the web editor to resolve and it caused the problem you see now on docdev.quantil.com.
Here, I'm trying to upload a file that definitely passes the JSON syntax checker on my machine:

burton@DESKTOP-ANPPPJ2 ~/github/docs-content-cdn/apispec
$  npx jsonlint ./openapi.json -q
npx: installed 8 in 2.149s

**Comment by burtonquantil** [comment]
By the way, I stage a preview of the help for our QA team to check here before generating the single file openapi.json required here.  It loads OK:
http://cdn360doc.quantil.com/apidocs/beta/cdn360doc.html
https://github.com/mileweb/cdn360API-OAS

**Review by nibinqtl — APPROVED** [review]
OK, let's give it a try on docdev

**Comment by burtonquantil** [comment]
Thanks. Unfortunately, GitHub  refuses to use the file I provided. It still complains about conflicts for some reason and disallows merge. It is asking me to do it on the command line. I will try that.

**Comment by burtonquantil** [comment]
I fixed by branching from dev and creating a new pull request https://github.com/mileweb/docs-content-cdn/pull/116  I merged it, and http://docdev.quantil.com/cdn/apidocs is now accessible. Sorry for the trouble.

**Pull request closed without merging**
