### PR TITLE
NCAS-2327 #comment checking in changes corresponding to sprint 90 (Re…

### PR DESCRIPTION
**Pull request by burtonquantil**
…lease18Sep2020)'s work.This has been reviewed by QA already

### CODE REVIEW

**Review by marcfishelquantil — COMMENTED** [review]
@burtonquantil Started reviewing the API, focusing on the Description text.

**Comment by burtonquantil** [comment]
@marcfishelquantil  you can look at the specific URLs in NCAS-2327 as well if that helps. It shouldn't take a huge amount of time. It is not necessary to go through the entire document as I made specific changes to some APIs only.

**Comment by marcfishelquantil** [comment]
@burtonquantil Got it, Burton. I'll upload a spreadsheet to Google Sheets when done, and then invite you and anyone else to view it.

**Comment by marcfishelquantil** [comment]
Posted suggested edits to API descriptions in Google Sheets for Burton to review.

**Comment by burtonquantil** [comment]
@marcfishelquantil  I created a separate pull request for those changes in another project and am awaiting review by you or a member of my team. That's the original project where I kept the OpenAPI spec. At the moment, I prefer to continue to use that and allow our QA team to verify changes before I merge here.

**Comment by marcfishelquantil** [comment]
@burtonquantil Sounds good, Burton.

**Review by marcfishelquantil — APPROVED** [review]
I approve these changes.

**Pull request merged**
